clear variables
load('metadata.mat');

nSubjs = size(metadata,2);
subjectFiles = cell(nSubjs,1);
DATAPATH = '/Users/Qihong/Documents/MATLAB/mridata/Manchester/data/newData/SIMILARITY/';
for i = 1 : nSubjs
    subjectFiles{i} = sprintf(strcat(DATAPATH,'subject%.2d.mat'), i);
end

% params = struct(...
%     'algorithm', 'soslasso', ...
%     'bias', false, ...
%     'alpha', 0.4200556,...
%     'lambda', 0.5863, ...
%     'shape', 'sphere', ...
%     'diameter', 18, ...
%     'overlap', 9,...
%     'cvscheme', 1, ...
%     'cvholdout', 1:10, ...
%     'finalholdout', 0, ...
%     'target', 'visual',...
%     'data', subjectFiles, ...
%     'data_var', 'X',...
%     'normalize', ...
%     'zscore', ...
%     'metadata',  strcat(pwd, '/metadata.mat'),...
%     'metadata_var', 'metadata', ...
%     'orientation', 'mni', ...
%     'filters', {{'ROI01','GoodRows'}}, ...
%     'SmallFootprint', false, ...
%     'debug', false,...
%     'SaveResultsAs','json');
% savejson('',params,'FileName','params.json','ForceRootName',false);
%
% WholeBrain_MVPA()



WholeBrain_MVPA(...
    'metadata', strcat(pwd, '/metadata.mat'),...
    'algorithm', 'soslasso',...
    'target','visual', ...
    'data'    ,subjectFiles , ...
    'data_var' , 'X'        , ...
    'metadata_var', 'metadata', ...
    'cvscheme'  , 1       , ...
    'cvholdout'    , 1, ...
    'finalholdout'   ,1  , ...
    'orientation'  ,'mni'    , ...
    'diameter'  ,1       , ...
    'overlap'   ,1       , ...
    'shape'      ,'cube'    , ... %
    'lambda'      ,10, ...
    'alpha'       ,0.2, ...
    'debias', false, ...
    'environment','chris')
